<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;net8.0;net10.0</TargetFrameworks>
    <Description>SD.AOP 面向方面编程基础</Description>
  </PropertyGroup>

  <ItemGroup Condition="$(TargetFramework.Equals('net462'))">
    <Reference Include="System.Configuration" />
    <Reference Include="System.Transactions" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.Equals('net8.0')) Or $(TargetFramework.Equals('net10.0'))">
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MrAdvice" Version="2.20.5" />
    <PackageReference Include="SD.Toolkits.Json" Version="4.0.2" />
  </ItemGroup>
</Project>
