<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>False</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SD.Toolkits.Sql" Version="4.0.2" />
    <PackageReference Include="SD.Toolkits.Sql.SqlServer" Version="4.0.2" />
    <PackageReference Include="SD.Infrastructure" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SD.AOP.Core\SD.AOP.Core.csproj" />
    <ProjectReference Include="..\SD.AOP.LogViewer.Repository\SD.AOP.LogViewer.Repository.csproj" />
  </ItemGroup>
</Project>
