<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;netstandard2.0;net8.0;net10.0</TargetFrameworks>
    <Description>SD.AOP - 日志提供者 - PostgreSQL实现</Description>
  </PropertyGroup>

  <ItemGroup Condition="$(TargetFramework.Equals('net462'))">
    <Reference Include="System.Configuration" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.Equals('netstandard2.0')) Or $(TargetFramework.Equals('net8.0')) Or $(TargetFramework.Equals('net10.0'))">
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SD.Toolkits.Sql" Version="4.0.0" />
    <PackageReference Include="SD.Toolkits.Sql.PostgreSQL" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SD.AOP.Core\SD.AOP.Core.csproj" />
  </ItemGroup>
</Project>
